### ISSUE TITLE
Expose ability to customize pressed state of a tab bar item

### ISSUE THREAD

**Issue by ghost** [alinz/react-native-tabbar#1]
Currently, when a tab bar item is pressed, there is no feedback at all. It would be great to be able to customize the tab bar item (change icon color, background of the item, etc, much like how buttons have a pressed state).

**Comment by alinz** [comment]
@leoskye Thanks and sorry for late update. We have updated the module by adding a lot of feature and more flexibility. Please feel free to reopen this ticket if you have the same problem!
