### ISSUE TITLE
How to use custom icons/icons with Tabbar?

### ISSUE THREAD

**Issue by robtg4** [alinz/react-native-tabbar#12]
Could you please add this example to the readme? Thanks!

**Comment by fuxinzhang** [comment]
it supports custom icons well before Dec 22 2015, but new commits are pushed, it doesn't seem to support custom icons!

**Comment by alinz** [comment]
@robtg4 @fuxinzhang I have extracted some logic from our app and created a new project called [react-native-pure-icon](https://github.com/alinz/react-native-pure-icon). This is what we do to use custom icon for our app. It works fine for both iOS and android.

The other thing is our tab will be pure View Component so you need to build everything. I will make a brand new example for this.

**Comment by robtg4** [comment]
Thanks! Much appreciated!

**Comment by fuxinzhang** [comment]
Thanks very much!

**Comment by fuxinzhang** [comment]
Thanks very much!

**Comment by alinz** [comment]
@robtg4 @fuxinzhang I have updated project with even more exciting feature. Take a look at the example
