### ISSUE TITLE
Requiring unknown module

### ISSUE THREAD

**Issue by paulbrie** [alinz/react-native-tabbar#13]
Hi, I've installed your module and it is present in my node_modules folder. However when I am trying to require it I have this error message in the appication: Requiring unknown module "react-native-tabbar/jsx/index.js".

Is there something I am missing?

Thanks,
Paul

![image](https://cloud.githubusercontent.com/assets/3997538/12241357/0d38c1ac-b893-11e5-8ea0-143d07639c06.png)

![image](https://cloud.githubusercontent.com/assets/3997538/12241371/184e7fbe-b893-11e5-8d62-2f19cd4c8631.png)

**Comment by alinz** [comment]
@paulbrie I have updated the project. Please take a look at the example folder. The doc is coming. please reopen this one if you still have this issue
