### ISSUE TITLE
How can I run Example?

### ISSUE THREAD

**Issue by AAG81** [alinz/react-native-tabbar#19]
Hi
How can I run the example code without copy/pase Codes?
Thanks

**Comment by alinz** [comment]
@AAG81 you simply clone the project, go to `example/WithIcons` folder. run `npm install` and either run `react-native run-android` to run on your android simulator or `open ios/WithIcons.xcodeproj` with xcode and run it there.

**Comment by AAG81** [comment]
Thanks a lot
example works fine in android but I have 2 problem in iOS
1- I can't simply type react-native run-iso I should open XCODE overtime
2- icomoon is missing in IOS build

**Comment by AAG81** [comment]
I followed the instruction [https://medium.com/@dabit3/adding-custom-fonts-to-react-native-b266b41bff7f#.x0vycwg9t](url) and add font to Xcode and it solved the font problem.
But I can't run project without opening Xcode.

**Comment by alinz** [comment]
I have also document how to use custom font and icons in this [repo](https://github.com/alinz/react-native-pure-icon).

What do you mean by `can't run the project without opening Xcode`?

if you upgrade the react-native to 0.19, it should be possible to simply run `react-native run-ios` inside the example or project to run it without xcode.

**Comment by AAG81** [comment]
Thank you I should update the project to 0.19
I have done it with this command  npm install --save react-native@0.19
