### ISSUE TITLE
null is not an object (evaluating StatusBarIOS.setStyle) -> On Android

### ISSUE THREAD

**Issue by BigPun86** [alinz/react-native-tabbar#2]
I used this Tabbar perfectly on my iOS Version, but trying to use it for my Android App crashes. Does it only work on iOS? I saw that in the Readme it is mentioned that it would work technically on Android, did someone get it working?

Best Regards

**Comment by alinz** [comment]
@BigPun86 if you could send me the whole error that would help a lot. But based on what I see, inside your app, you are referring to `StatusBarIOS`. that module only exists in ios. I don't see it in my module. So double check your app and see where you are using `StatusBarIOS`.

**Comment by BigPun86** [comment]
@alinz Okay thanks for the advice, i will trace it it and try to solve it. Here is my error output from the emulator:

![screen shot 2015-10-20 at 09 39 37](https://cloud.githubusercontent.com/assets/7880624/10600988/a886e308-770e-11e5-876f-688992924638.png)
![screen shot 2015-10-20 at 09 39 53](https://cloud.githubusercontent.com/assets/7880624/10600989/a88a02cc-770e-11e5-879c-448492ddeb57.png)

**Comment by alinz** [comment]
This should be fixed by new released. Please try again with new module. Be warned that some of the api has been changed.
