### ISSUE TITLE
Again Styles

### ISSUE THREAD

**Issue by AAG81** [alinz/react-native-tabbar#20]
I have read closed Issues, But still I can't style the tabbar.
I want a tab bar without a border. and also want to change the color of font when it is selected.
How can I change these parameters?
`const color = selected? onActiveColor : onInactiveColor`
    `const barColor = selected? onActiveColorBar : onInactiveColorBar;`
    `const borderWidth = selected? 2 : 1;`
    `const padding = selected? 0 : 1;`

**Comment by alinz** [comment]
@AAG81 you should know that this library is low level. So It manages all the tabs and contents but it doesn't dictate the way. you have to implement your Icon by extending RawIcon. post your simple requirement with a little bit of picture and I will guide you through.

**Comment by AAG81** [comment]
First of all thanks for your quick responses.
There is a border on top of Tabbar which is black, whenever I select a tab the border
become red and thicker I want to **_remove_** a border at both state.
About the icon I want to change the default color to black and when I select the tab the icon become **red**
instead of white.

**Comment by AAG81** [comment]
I think it would be good idea if you change the code the way that we could give style to each component(tabBar,tab,IconWithBar) through standard style attribute.

**Comment by alinz** [comment]
@AAG81 the new version let's you style everything. closing this ticket.
