### ISSUE TITLE
Rotate Problem

### ISSUE THREAD

**Issue by AAG81** [alinz/react-native-tabbar#21]
When I rotate the phone Tabbar would not extend to fill the screen. I attached the screenshot.
![rotate](https://cloud.githubusercontent.com/assets/8626202/12852877/706f5f1c-cc46-11e5-9237-95d205abc949.png)

**Comment by adamski** [comment]
Maybe something like https://github.com/DrMabuse23/react-native-device-orientation could be used to fix this issue?

**Comment by adamski** [comment]
Fixed #31

**Comment by alinz** [comment]
Hi @AAG81 I decided to take another approach. I have fixed this one without using onLayout change. onLayout change is very tricky and it leads to performance problem. I have pushed new code and please look into examples.
