### ISSUE TITLE
How to custom tab icon?thanks!

### ISSUE THREAD

**Issue by peng051410** [alinz/react-native-tabbar#26]

**Comment by rainer-liao** [comment]
+1

**Comment by yizzuide** [comment]
+1

**Comment by adamski** [comment]
Yes it would be nice to be able to add an image instead of using a font icon as in the example. I guess the answer to this is like #14 - have a look at the current Icon components and submit a PR!

**Comment by alinz** [comment]
@peng051410 @rainer-liao @yizzuide and @adamski, the new approach makes it really easy to use image. the content of Tabbar will be all control by you. take a look at the example folder.
