### ISSUE TITLE
undefined is not an object (evaluating 'screenPhysicalPixels.width') -> On Android

### ISSUE THREAD

**Issue by naivehhr** [alinz/react-native-tabbar#27]
Which files using code 'screenPhysicalPixels.width'?

![1](https://cloud.githubusercontent.com/assets/5243456/13456810/e6c7a9d6-e09f-11e5-814c-685e63e6380b.png)

**Comment by marcelglaeser** [comment]
+1

**Comment by qxqxqxqx** [comment]
+1

**Comment by fultonm** [comment]
http://stackoverflow.com/questions/35609603/react-native-android-screenphysicalpixels-width-is-undefined

The first answer here solved this problem for me.

**Comment by alinz** [comment]
not relevant anymore since, the new version fixes the probelm
