### ISSUE TITLE
Error: "RCTWebSocketModule.connect was called with 4 arguments, but expects 2"

### ISSUE THREAD

**Issue by adamski** [alinz/react-native-tabbar#30]
I get the following error trying to run the WithIcons examples project:

`RCTWebSocketModule.connect was called with 4 arguments, but expects 2`

**Comment by alinz** [comment]
@adamski would you try with new version. Unfortunately, I didn't like the previous implementation. I made every thing too complicated. let me know if you find any problem or suggestion.
