### ISSUE TITLE
How to place tabbar in top of page?

### ISSUE THREAD

**Issue by susylPearl** [alinz/react-native-tabbar#32]
i have made tabbar at the bottom of screen but i need it at top of the screen. Will it be possible?

**Comment by JerryAWalker** [comment]
yes

**Comment by susyl13** [comment]
How can you suggest me ?

**Comment by JerryAWalker** [comment]
you will have to make changes in libs/bar/dynamic.js
so change 
//
 show(enable, duration) {
    const { size } = this.props;
    // change size from -size to +size
    const toValue = !!enable? 0 : +size;
    this._sizeLimit.reset(!!enable? size : 0);
    Animated.timing(this.value, {
      duration: duration,
      toValue
    }).start();
}
//in render() change
from
// its styled absolute so change bottom to top
Rawbar style={[style, { height: size, bottom: this.value }]}
to
Rawbar style={[style, { height: size, top: this.value }]}

keep me posted :)

**Comment by susylPearl** [comment]
Thanks a lot. :+1:

**Comment by alinz** [comment]
closing this ticket.
