### ISSUE TITLE
Custom Icon's text fontSize.

### ISSUE THREAD

**Issue by nuqiewuoz** [alinz/react-native-tabbar#36]
now the text's font size is hard coded as 12,

```
      <View style={{ paddingTop: 5 }}>
        <Text style={{ fontSize: 12, color: color }}>{label}</Text>
      </View>
```

I think it's better to add a prop for the text style.

**Comment by alinz** [comment]
@nuqiewuoz completely agree, the new version let's you customize everything. the api has been changed alot. try it and give me some feedback. closing this ticket.
