### ISSUE TITLE
Slow performance on device

### ISSUE THREAD

**Issue by adamski** [alinz/react-native-tabbar#39]
I'm getting very slow response times testing on a device. Takes a few seconds to switch tabs. Sometimes unresponsive. Need to look into whats causing it but thought I would raise it here. Made sure my bundle is not in dev mode and app is compiled in release mode. 

Device is iPhone 4S iOS 7.1

**Comment by alinz** [comment]
@adamski can you provide an example here. even a gist would be good enough for me.

**Comment by adamski** [comment]
Actually in the example app on the device, its slow (around 2 secs) to load the view with the large list. Others take about 0.5 secs to respond.  

My app has a native view which takes about 2-3 seconds to load as a tab

**Comment by alinz** [comment]
@adamski if you are still having this issue, reopen this ticket. remember, I have introduce the new version of this library.
