### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by christinwilson** [alinz/react-native-tabbar#40]
how to use this tabbar.. I dont seem to find a proper documentation for this.

**Comment by derdav3** [comment]
look at "react-native-tabbar/example/WithIcons/app.js"

`<Tabbar ref="myTabbar" barColor={'gray'} onLayout={this.onLayout}>
        <Tab name="home">
          <IconWithBar label="Home" type={glypy.Home} from={'icomoon'}/>
          <RawContent>
            <View style={{ flex: 1, backgroundColor: 'white', alignItems: 'center', justifyContent:'center' }}>
              <Text onPress={()=>this.tabbarToggle()}>Toggle Tabbar</Text>
            </View>
          </RawContent>
        </Tab>
        <Tab name="camera">
          <IconWithBar label="Camera" type={glypy.Camera} from={'icomoon'}/>
          <RawContent>
            <View style={{ flex: 1, backgroundColor: 'white', alignItems: 'center', justifyContent:'center' }}>
              <Text onPress={()=>console.log('camera')}>Camera</Text>
            </View>
          </RawContent>
        </Tab>`

**Comment by alinz** [comment]
@christinwilson can you try the new version. I did 2 common examples and the api has been simplified a lot.
