### ISSUE TITLE
The content appears to 'reload' when clicking back to a tab unlike TabbarIOS

### ISSUE THREAD

**Issue by MossP** [alinz/react-native-tabbar#5]
Is there a way to avoid this?

Ps. This is great. It works on Android, out-of-the-box, too.
Thanks @alinz !

**Comment by alinz** [comment]
@MossP can you test this with new release. Please reopen this with more details if you still have this issue.

**Comment by MossP** [comment]
I can't see a fix for this, but then again, the example no longer works for me so the error might be my side.. Now it's always the last tab in the list that shows regardless of which tab i have clicked

**Comment by alinz** [comment]
@MossP I'm working on rewriting this module, We have not seen your issue yet, but give us a few days and as soon as I finished the new improved version I will let you know.
