### ISSUE TITLE
No update when clicking between two navigator items

### ISSUE THREAD

**Issue by MossP** [alinz/react-native-tabbar#6]
If you were to have the following:

Tab1 : Navigator 1 with Component A as initial stack item
Tab2 : Navigator 2 with Component B as initial stack item
Tab3 : Empty View

Clicking between Tabs 1 and 2 will not change the content, but clicking to tab3 then back to either Tab1 or 2 will update the content correctly (albeit it having lost its previous 'state').

**Comment by nbastoWM** [comment]
I had the same issue. Try to add a different "key" parameter in each of the first components.

**Comment by MossP** [comment]
Thanks @nbastoWM I will give it a try. I ended up writing a temporary one myself but this could be helpful.

**Comment by alinz** [comment]
@MossP we have a major update on tabbar module. Please take a look at this. I think  we addressed this issue. Please feel free to open this ticket if this issue still exists.
